# Generated by Django 3.0 on 2019-12-25 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
