# Generated by Django 3.0 on 2019-12-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0002_item_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
