# Generated by Django 3.0 on 2019-12-26 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Invent', '0003_auto_20191225_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.CharField(max_length=100, null=True),
            preserve_default=False,
        ),
    ]
