# Generated by Django 3.0 on 2019-12-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0004_item_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='author',
            new_name='user',
        ),
    ]
