# Generated by Django 3.0 on 2019-12-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0005_auto_20191226_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
