# Generated by Django 3.0 on 2019-12-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0007_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
