# Generated by Django 3.0 on 2019-12-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0008_remove_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.IntegerField(null=True),
        ),
    ]
