# Generated by Django 3.0 on 2019-12-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0009_item_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_code',
        ),
    ]
