# Generated by Django 3.0 on 2019-12-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0010_remove_item_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('item_code', models.IntegerField()),
            ],
        ),
    ]
