# Generated by Django 3.0 on 2019-12-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0011_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='item_code',
            new_name='code',
        ),
    ]
