# Generated by Django 3.0 on 2019-12-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0012_auto_20191226_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='code',
            new_name='item_code',
        ),
        migrations.RemoveField(
            model_name='log',
            name='company_name',
        ),
    ]
