# Generated by Django 3.0 on 2019-12-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0014_item_item_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='log',
            new_name='legger',
        ),
    ]
